language: java
jdk:
  - oraclejdk11
script: mvn clean install

branches:
  only:
  - master
  - development

jobs:
  include:
    - stage: Test
      script: mvn clean test

notifications:
  email: bwg66976@zwoho.com
